# Site settings
title:          Patryk Olejniczak
description:    "Description loading in progress..."
url:            "https://patrykolejniczak.github.io"

# Author
author:
  name:         Patryk Olejniczak
  url:          https://patrykolejniczak.github.io
  email:        patryk.olejniczak.blog@outlook.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       8
